# Make sure this is set to "kotlinforforge"
modLoader="kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion="[3,)" # Require at least 3.x
# License is REQUIRED after 1.16
license='LGPL'

[[mods]]
modId="chasium"
version="${file.jarVersion}"
displayName="Chasium"
credits="Cimetiere des Innocents"
authors="Chlamydomonos"
description='''
一个拥有科技线和魔法线的物流Mod
'''
[[dependencies.chasium]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.chasium]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
